View events fullstack
cornellh4i/lagos-volunteers pull request #123
Opened 2023-10-23 03:17 UTC by snehar27

## Summary

Closes #96.

## Testing

Run yarn `run start` and navigate to http://localhost:3000/events/view

## Notes

The data array for the tests would be empty because the enrolled users in the database are not enrolled in any events.

2023-11-14 17:47 UTC, akinfelami requested changes
<img width="1241" alt="Screenshot 2023-11-14 at 12 46 33" src="https://github.com/cornellh4i/lagos-volunteers/assets/59776300/e680507d-d7e7-40aa-8a5f-e5de8192ae82">
This is what I see on the ViewEvents page

2023-11-14 17:47 UTC, akinfelami commented on frontend/src/components/organisms/ManageUsers.tsx
This file should not be in this PR

2023-11-18 20:44 UTC, akinfelami approved these changes

2023-11-20 22:08 UTC, akinfelami requested changes
Please remove `ManageUsers.tsx` from this PR. You didn't need to make any changes to this file please remove it

2023-11-22 03:24 UTC, akinfelami approved these changes

2023-12-19 06:23 UTC, jasozh approved these changes

2023-12-19 06:23 UTC, merged