Location picker frontend
cornellh4i/lagos-volunteers pull request #130
Opened 2023-11-11 00:48 UTC by Y1chenYao

## Summary
- implement location picker with google api autocompletion integrated
- closes #127 

## Testing
- run `yarn add react-google-autocomplete` install the [package](https://www.npmjs.com/package/react-google-autocomplete#reactgoogleautocomplete)
> actually we might to do this on our end?
- go to `baseurl/events/create`
- click in-person and type to click an addresses
- open console to see the log of the address

![image](https://github.com/cornellh4i/lagos-volunteers/assets/68068854/2266cb56-301b-48b3-a5a5-6f9d43f3d407)

## Notes & Resources for Full-stack
- The `AutoComplete` component should be treated as a `html <input>` for styling. For more documentation, see the links below.
- Package link: https://www.npmjs.com/package/react-google-autocomplete#reactgoogleautocomplete
- Google api doc: https://developers.google.com/maps/documentation/javascript/place-autocomplete#constrain-place-types

2023-11-20 21:58 UTC, akinfelami requested changes
Solid work on this guys! 

Everything looks fine to me. The only thing is make sure to add the `package.json` for the frontend folder. It will include the new entry for react-autocomplete... so that other devs can just install it

2023-11-22 02:44 UTC, Y1chenYao commented
Fild added!

2023-11-22 03:09 UTC, DannyThorne01 reviewed
Great Work!!

2023-11-22 03:09 UTC, DannyThorne01 commented on frontend/package.json
Is this `package.json` required in the PR?

2023-11-22 05:10 UTC, akinfelami approved these changes

2023-11-22 05:11 UTC, akinfelami commented on frontend/package.json
Yep! `react-google-autocomplete` was added to the dependencies

2023-11-22 05:13 UTC, DannyThorne01 approved these changes

2023-11-30 23:07 UTC, louisvalencia approved these changes
Very clean code and the feature works as expected! woooo 🕺🏻

2023-12-20 00:30 UTC, jasozh approved these changes

2023-12-20 03:18 UTC, merged