About page frontend
cornellh4i/lagos-volunteers pull request #131
Opened 2023-11-13 08:14 UTC by snehar27

## Summary

Closes #111

## Testing

When testing, run the following code:

```
import React from "react";
import About from "@/components/organisms/About";

const Test = () => {
  return <About edit={true} />;
};

export default Test;
```

Then, run `yarn run start` and navigate to `http://localhost:3000/Test`

## Notes

There may be a few importing errors because we had to add to the `package.json` file to implement the rich text editor, but `package.json` was not pushed.

2023-11-20 22:11 UTC, akinfelami requested changes
Hey guys!

Please see the changes I requested in this PR

2023-11-20 22:11 UTC, akinfelami commented on frontend/src/components/organisms/About.tsx
> +  // }
please remove all this commented out code?

2023-11-20 22:11 UTC, akinfelami commented on frontend/src/components/organisms/About.tsx
> +    // <ViewEvents />;
why comment this out? Did you look into what I asked regarding using JSX components in react-quill?

2023-11-20 22:11 UTC, akinfelami commented on frontend/src/components/organisms/ManageUsers.tsx
Please remove this file. It should not be in this PR

2023-11-20 22:11 UTC, akinfelami commented on frontend/src/components/organisms/ViewEvents.tsx
PLEASE remove this file. It should not be in this PR

2023-11-20 22:11 UTC, akinfelami commented on frontend/src/components/organisms/About.tsx
> +  </Modal>;
Please open the `Test` page where and tell me if you see this part?

2023-11-20 22:11 UTC, akinfelami commented on frontend/src/components/organisms/About.tsx
> +  if (edit == true) {
You don't need this at all. I think I even mentioned to remove the prop entirely from the component. The component is already editable with react-quill

2023-11-25 06:52 UTC, akinfelami reviewed
About page is not there. There is still a decision to be made on how we want to format the html + render JSX components together (e.g EventCards). React-quill does not support this out of the box. 
Also it includes file that should not be in this PR. I have attempted to remove to no success

2023-12-03 03:05 UTC, akinfelami approved these changes

2023-12-20 00:49 UTC, jasozh approved these changes

2023-12-20 00:49 UTC, merged