Update dependencies
cornellh4i/lagos-volunteers pull request #145
Opened 2024-02-08 21:21 UTC by jasozh

## Summary

Update dependency versions in `package.json`. Did some preliminary testing to make sure nothing was broken.

2024-02-08 22:38 UTC, akinfelami reviewed
Can we leave this open for now ? until we merge the other large PR. I don't assume anything will be broken, but for good measure, I say we merge this after testing with that PR

2024-02-09 04:14 UTC, jasozh commented
I think it should be fine because we can always revert back to the old yarn.lock and package.json versions if an issue does come up. I wasn't able to find any issues but feel free to test it whenever you're free. I think reading through the changelog might be a bit too much, but I understand the concern.

2024-02-10 02:15 UTC, akinfelami commented on frontend/package.json
> +    "next": "^14.1.0",
https://nextjs.org/blog/next-14#other-changes

2024-02-29 00:25 UTC, akinfelami approved these changes

2024-02-29 00:29 UTC, akinfelami requested changes
hold off to fix  merge conflicts

2024-02-29 16:59 UTC, akinfelami approved these changes
good to go!

2024-03-15 01:13 UTC, merged