Search bar fullstack
cornellh4i/lagos-volunteers pull request #191
Opened 2024-03-16 23:34 UTC by ArushiAggarwal

## Summary

Allows a user to search for a specific member in the "Manage Members" and "Manage Attendees" using the search bar.

## Testing

1. Navigate to http://localhost:3000/users/view and http://localhost:3000/events/cltqat83d0008quy2rua733xc/attendees
2. Search for a user and press enter or press the search icon in the search bar

## Notes

2024-03-22 15:32 UTC, akinfelami requested changes
Hi guys!

Great work on this! 

I have added some comments to the PR. It will need some more attention before it is ready to be merged, but you guys are on a great start! let me know if there are any questions!

2024-03-22 15:32 UTC, akinfelami commented on frontend/src/components/organisms/ManageAttendees.tsx
> +      );
With this query, you can search for a user that is not part of the attendee list of an event, and the query will return a result which is not ideal

2024-03-22 15:32 UTC, akinfelami commented on frontend/src/components/organisms/ManageUsers.tsx
> +          `/users?firstName=${searchQuery}`
One thing I noticed is that the searching is case-sensitive. Please take a look at this: https://www.prisma.io/docs/orm/prisma-client/queries/case-sensitivity#:~:text=%7D)-,Options%20for%20case%2Dinsensitive%20filtering,-The%20recommended%20way

to see how case insensitive filtering would work in Prisma

2024-04-12 05:46 UTC, jasozh approved these changes

2024-04-12 05:50 UTC, merged