Got global sorting on email column. Still have to fix cursor issue
cornellh4i/lagos-volunteers pull request #192
Opened 2024-03-17 03:58 UTC by dvala041

## Summary

<li> Added properties to the table component for server-side global sorting
<li> modified useEffect() in ManageUser.tsx to perform the server-side sorting
<li> still have to fix issue with cursor being used more than once when refetching

## Testing

<li> tested by using console.log()

## Notes
<li> Once again still some changes we have to make for this to work correctly. 
<lI> Also the other files that use tables must be adjusted as they are throwing errors

2024-03-22 17:45 UTC, akinfelami requested changes
Folks, great work on this!

I have added some code and I believe the sorting is now functional. Please test this to confirm. 

Additionally, please remove commented out code. but leave necessary comments. Also remove any unnecessary logs. 

Finally address the comments I have included in the PR. Great job!

2024-03-22 17:45 UTC, akinfelami commented on backend/src/users/controllers.ts
> +  // console.log(queryResult);
remove comments.

2024-03-22 17:45 UTC, akinfelami commented on frontend/yarn.lock
remove this file

2024-03-27 22:40 UTC, dvala041 commented
### Fixes

<li> included sortingOrder property in datagrid component in tables.tsx

### Bugs

1. When staleTime is infinity in the Tanstack query, the next pages don't change when we change sort order
2. Even when we comment out the staletime line there is another bug:
a. When we're on say page 4 and hit the sort button, the sort mode changes but page 0 doesn't change. If we traverse to the next pages the data is all wrong. 
b. Akin noted that the data is being fetched again every time we change pages which isn't intended behavior (should only be fetched when sorting model changes)

2024-05-20 17:58 UTC, akinfelami reviewed
new pagination model and sorting model that seems to work. Deprecates all that prefetching we used to do. Lmk what you think

2024-05-20 17:58 UTC, akinfelami commented on backend/src/users/controllers.ts
>      };
this is to address the case of passing an empty cursor, if an empty cursor is passed, the backend should be able to ignore it.

2024-05-20 17:58 UTC, akinfelami commented on backend/src/users/controllers.ts
> +
more on passing empty cursor

2024-05-20 17:58 UTC, akinfelami commented on backend/src/users/controllers.ts
> +  };
New design here:

Based on cursor pagination. NextCursor is the id of the last user returned for this batch. We will use this to fetch the next batch (basically users after this id in the db). PrevCursor is the id of the first user in the batch. So if we need to fetch a previous page, we just take the users before that id

2024-05-20 17:58 UTC, akinfelami commented on backend/src/users/controllers.ts
> +  };
This also means that all components that used to consume this endpoint will break because what this returns has changed

2024-05-20 17:58 UTC, akinfelami commented on frontend/src/components/organisms/ManageUsers.tsx
> +   * @returns the current page of users (with respect to the current pagination and sorting states)
I tried to put comments on some of these functions so they are not too difficult to follow, the order I put them is a good way to understand what they are doing

2024-06-02 01:48 UTC, jasozh commented
I like this. So basically we have a `prevCursor` and a `nextCursor` which defines the start and end of the batch, and we use the `prevCursor` to grab the previous page and `nextCursor` to grab the next page. Tested it out and it looks like sorting actually works which is pretty awesome.

2024-06-15 03:00 UTC, closed without merging