Prune unverified users backend
cornellh4i/lagos-volunteers pull request #201
Opened 2024-03-23 22:23 UTC by owenchen04

## Summary

Added helper function `deleteUnverifiedUsers` in `helpers.ts` to delete users with an unverified email from firebase and the local database. Schedules the function to run in `server.ts` every 24 hours as a cron job. Only deletes unverfied users if they were created over 24 hours ago (to prevent users from being deleted immediately after they create their account but haven't yet verified it).

## Testing

We used manual testing on individual dummy users since we couldn't directly try deleting every unverified user from firebase (as most users are currently unverified). We started by console.log-ing every user and whether or not they're verified. We then picked a specific user and added an additional if-branch to just delete that user, checking to make sure they were deleted in both firebase and the local database.

## Notes

- **WARNING**: be careful when un-commenting code, as you might unintentionally delete most of the users in firebase if you just let it run. To test, switch the cron job in `server.ts` to run every minute, then pick a user to test on and add an if-branch inside `deleteUnverifiedUsers` to just delete that user.

2024-03-27 17:44 UTC, akinfelami requested changes
Hey guys!

Great work on this! Just one comment that we can chat about. Let me know!

2024-03-27 17:44 UTC, akinfelami commented on backend/src/utils/helpers.ts
> +
What happens if any of these throw an error?

2024-04-02 18:38 UTC, akinfelami approved these changes
Last commit to fix merge conflicts!

2024-04-02 19:24 UTC, akinfelami commented
Okay, last comment here: 
Last introduction of websockets, introduced issues to the test suites. In additional to some other fixes, Got around to address them in this PR, and as you can see, checks pass now. 

Now, some of the other PRs are good to go, but they still fail the CI tests. I can cherry pick the commits from here into those PRs, to make sure checks pass and no merge conflicts, but I imagine they will get bloated. Lmk what you think!

2024-04-04 21:11 UTC, jasozh approved these changes

2024-04-04 21:11 UTC, merged