Created Modal in ProfileForm.tsx, added profile deletion from firebas…
cornellh4i/lagos-volunteers pull request #230
Opened 2024-04-14 03:51 UTC by dvala041

# H1 Account-Deletion-FullStack

## Summary
1. Created changeUserStatus function in ProfileForm.tsx which makes a call to /users/:userid endpoint to delete user from prisma and firebase databases (added ability to delete from firebase database in views.ts)
2. Created a Modal for deleting account in ProfileForm.tsx; when account is deleted the user's session ends, they are rerouted to login page and their account is deleted

## Testing
1. Created dummy accounts to test the endpoint on postman and then on our local code

## Notes
1. Akin noted the importance of having the prisma and firebase deletion in the same promise

2024-04-17 03:16 UTC, akinfelami requested changes
Hi guys, great work on this!

I have added a few comments that need addressing. Please check them out and let me know if there are any questions

2024-04-17 03:16 UTC, akinfelami commented on frontend/src/components/organisms/ProfileForm.tsx
> +        console.log("DELETED");
remove log

2024-04-17 03:16 UTC, akinfelami commented on frontend/src/components/organisms/ProfileForm.tsx
> +  const { mutateAsync: changeUserStatus, error: changeUserStatusError } =
You should use appropriate naming patterns. I don't think `changeUserStatus` is the way

2024-04-17 03:16 UTC, akinfelami commented on frontend/src/components/organisms/ProfileForm.tsx
> +    await handleSignOut();
Wrap this in a try catch, it is possible that it fails and the user will need some feedback that the action failed

2024-04-17 03:16 UTC, akinfelami commented on frontend/src/components/organisms/ProfileForm.tsx
> +
remove comments

2024-04-17 03:16 UTC, akinfelami commented on frontend/src/components/organisms/ProfileForm.tsx
> +          </div>
I saw some experimentation with making the Delete account button disabled until the user enters the right email. I think it's a good idea. Let's keep that

2024-04-24 01:47 UTC, akinfelami approved these changes

2024-05-06 21:34 UTC, akinfelami approved these changes

2024-06-09 00:10 UTC, jasozh approved these changes

2024-06-09 00:13 UTC, merged