Log in with Google
cornellh4i/lagos-volunteers pull request #243
Opened 2024-04-22 03:36 UTC by owenchen04

## Summary

Allowed users to create an account and sign-in using the 'Continue with Google' button. The flow is the same regardless of whether they are using Google to log in for the first time or they are a returning user.

## Testing

Manually tested by using my personal Google account. Made sure that in both cases (first time signing in vs. returning user), continue with Google worked as expected (creating a user in the local database in the former case). Also used console.log to ensure that the created firebase user had emailVerified already set to true.

## Notes

I was having issues using the react-firebase-hooks useSignInWithGoogle hook, as the googleUser object returned by the hook was always undefined. Instead, I followed the official firebase documentation. While the flow seems fine for now, there is a possibility that there are errors I couldn't account for.

2024-04-24 03:56 UTC, akinfelami requested changes
Hi guys!

Nice work on this. I tested it and it works fine! However, I noticed some things that will need your attention. Please see my comments

2024-04-24 03:56 UTC, akinfelami commented on backend/src/users/views.ts
> +
You don't need all this. Since it's just one action, simply use the patterns of `attempt` that other endpoints use

2024-04-24 03:56 UTC, akinfelami commented on backend/src/users/views.ts
> +
You will actually need to set the user's custom claims in this controller

2024-04-24 03:56 UTC, akinfelami commented on frontend/src/components/organisms/LoginForm.tsx
> +    const provider = await new GoogleAuthProvider();
no need to await this?

2024-04-24 03:56 UTC, akinfelami commented on frontend/src/components/organisms/LoginForm.tsx
> +      createUser();
createUser is an async function but you don't await this or use then/catch

2024-04-24 03:56 UTC, akinfelami commented on frontend/src/components/organisms/LoginForm.tsx
> +          await createLocalUserFromGoogle.mutateAsync({userid, firstName, lastName, email, phoneNumber});
this can potentially throw an erorr but there is no error management for it

2024-05-06 23:06 UTC, akinfelami approved these changes

2024-06-14 00:55 UTC, jasozh commented
Thinking about potential issues:

1. User creates email/password account then Google account. No issue here, the Google account automatically links to the email/password account in Firebase. ISSUE: "Your account already exists. Please log in using your email and password." error never triggers. Consider removing? Having an automatic link is desired behavior imo.
2. User creates Google account thatn email/password account. Resetting their password is the only way to change their password (to create an email/password account), and doing so also replaces their Google account in Firebase with email/password. But no user-facing issue, because signing into Google automatically links their accounts again. So maybe a non-issue?

2024-06-15 05:20 UTC, jasozh approved these changes

2024-06-15 05:20 UTC, merged