Implement signup cap in ManageAttendees and ViewEventDetails
cornellh4i/lagos-volunteers pull request #265
Opened 2024-06-19 18:58 UTC by jasozh

## Summary

Show the volunteer signup cap properly and prevent volunteers from signing up when exceeding the limit. Also implement WebSockets so that the number of registered volunteers automatically refreshes when the user cancels their registration or is canceled by the supervisor. Finally, volunteers can no longer cancel if the supervisor moves them away from PENDING.

Closes:
- Prevent volunteers from signing up if the volunteer signup cap is already reached

## Testing

![image](https://github.com/cornellh4i/lagos-volunteers/assets/48730262/0de7aa8e-b21f-4389-8ac3-1eb7e95cec1b)
![image](https://github.com/cornellh4i/lagos-volunteers/assets/48730262/e9edd300-6308-4ff0-8c0a-a9e9e2ed8992)

## Notes

2024-06-20 03:46 UTC, akinfelami commented
This is good. The websockets are also clutch. However, I think we need to add server side to complete it.

2024-06-20 03:46 UTC, akinfelami requested changes

2024-06-20 03:46 UTC, akinfelami commented on backend/src/events/controllers.ts
> +      attendees: true,
the comment to you pr also applies here

2024-06-20 03:46 UTC, akinfelami commented on frontend/src/components/organisms/ManageAttendees.tsx
> +      queryClient.invalidateQueries({ queryKey: ["event"] });
Was this key created anywhere?

2024-06-20 03:46 UTC, akinfelami commented on frontend/src/components/organisms/EventCardCancel.tsx
> +            have passed the window for canceling your registration. Registration
nit- missing 'You'

2024-06-20 05:05 UTC, jasozh commented
Moved client-side filtering to the backend and created 2 new API endpoints. This means we can get rid of calling the entire attendees object.

2024-06-20 05:06 UTC, jasozh commented
> This is good. The websockets are also clutch. However, I think we need to add server side to complete it.

What do we need to implement on the server-side? Tested it in two windows and it seems to work as is.

2024-06-21 02:52 UTC, akinfelami commented
> > This is good. The websockets are also clutch. However, I think we need to add server side to complete it.
> 
> What do we need to implement on the server-side? Tested it in two windows and it seems to work as is.

Basically, validations like you can't sign up because the event is full. The server should throw an error if that's the case

2024-08-11 21:36 UTC, jasozh commented
Added server-side validation. Merging the PR as is but lemme know if you have any other concerns.

2024-08-11 22:03 UTC, merged