Create login/signup layout page
cornellh4i/lagos-volunteers pull request #50
Opened 2023-04-17 07:42 UTC by snehar27

## Summary

Closes #40
Implemented `WelcomeTemplate.tsx` and imported `WelcomeTemplate.tsx` into `login.tsx` and `signup.tsx` to create a layout for the login and signup pages.

## Testing
Steps:
Run `yarn run dev`

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/81458184/232417543-ae340794-f53a-44ce-bfe0-ff85069b11bd.png">

## Notes
There is padding added around the left part of the grid with approximate dimensions.

2023-04-18 03:01 UTC, jasozh requested changes

2023-04-18 03:01 UTC, jasozh commented on frontend/src/pages/login.tsx
`WelcomeTemplate` should be imported from the `components` folder and not the `pages` directory. Check the Frontend Onboarding Guide to see how to do this.

2023-04-26 23:12 UTC, jasozh approved these changes

2023-04-27 02:53 UTC, akinfelami approved these changes

2023-04-27 02:53 UTC, merged