Added modal component
cornellh4i/lagos-volunteers pull request #90
Opened 2023-09-19 04:12 UTC by sophwa

Closes #84 

## Summary

Fully implemented modal component 

- Added two parameters from original release code: title and text
- Added background box design
- Added two buttons 

## Testing

Run yarn run start from frontend folder

2023-09-19 14:52 UTC, akinfelami requested changes
Hi! Can you get a little more specific on how to test the modal? I want to see what it looks like on the page? Kindly get to this and I can offer some more feedback on the code.

2023-09-19 14:52 UTC, akinfelami commented on frontend/src/pages/profile.tsx
> +import { Modal } from "@mui/material";
Here you import `Modal` from material UI but we already have a custom built modal in `molecules/Modal`

2023-09-19 14:52 UTC, akinfelami commented on frontend/src/pages/events/view.tsx
> +import Modal from "../../components/molecules/Modal";
I assume you import Modal in this page to test it. But where does this happen?

2023-09-19 15:12 UTC, akinfelami requested changes

2023-09-19 15:12 UTC, akinfelami commented on frontend/src/components/molecules/Modal.tsx
> +        </Typography>
Kindly use https://mui.com/material-ui/react-modal/. It is hard to make a modal from scratch using tailwind

2023-09-22 01:21 UTC, Y1chenYao requested changes
- `title` and `text` are not passed in as props. We need to make those customizable. Also the `body` prop is passed in but never used.
- The styling looks fine to me though. :)
<img width="676" alt="image" src="https://github.com/cornellh4i/lagos-volunteers/assets/68068854/7c872079-c334-4a99-b734-be0d8466bea4">

2023-09-23 01:24 UTC, bananahz commented
Can you attach some screenshots to the PR? Not necessary I think but nice to have for documentation purposes

2023-09-23 01:28 UTC, bananahz requested changes

2023-09-23 01:28 UTC, bananahz commented on frontend/package.json
Try not to add all the files you've changed to the PR, only the ones you actually want to push. I'm assuming `git add .` was used, which usually you want to avoid in case you push files you dont mean to.

2023-09-23 01:28 UTC, bananahz commented on frontend/yarn.lock
remove this file from the PR

2023-10-08 21:45 UTC, merged