Added implementation for EventConfirmation.tsx
cornellh4i/lagos-volunteers pull request #91
Opened 2023-09-19 09:57 UTC by snehar27

## Summary

Implemented EventConfirmation.tsx.

2023-09-19 14:43 UTC, akinfelami commented
This doesn't meet the standards for making a PR. The description is vague. How do I test it? Are there any notes?

2023-09-19 14:45 UTC, akinfelami requested changes
Hi! I don't know how to see the changes you made. Can you make the PR more descriptive and offer a way to test it? Then I can offer some more feedback on the code.

2023-09-19 14:45 UTC, akinfelami commented on frontend/src/components/molecules/CardList.tsx
> +// import EventCard from "@/components/molecules/EventCard";
It looks like the only change to this file is this commented out line. Remove it if it is not of any use

2023-09-22 01:19 UTC, Y1chenYao requested changes
- The icon/headline/link should be styled (centered/grey color, etc). 
<img width="497" alt="image" src="https://github.com/cornellh4i/lagos-volunteers/assets/68068854/d07524e3-b72c-40c7-8430-2b7dca60918e">

- Some components can be replaced with `EventDetails.tsx` as a placeholder. 
- Rather than `if "rsvp" else if "not rsvp"`, I recommend using a boolean value to represent `rsvp` action. During testing, I got the error of possibly null return value, which is due to the fact that if we have an action that is neither "rsvp" nor "not rsvp", nothing will be returned.

2023-09-23 01:31 UTC, bananahz commented on frontend/src/components/organisms/EventConfirmation.tsx
> +            cancel here
add a space here

2023-09-23 01:32 UTC, bananahz commented
Building off Yichen's comment, on figma if you go to dev mode, theres exact specifics for styling (rem, color, etc.) :)

2023-09-23 01:32 UTC, bananahz requested changes

2023-09-23 01:32 UTC, bananahz commented on frontend/src/components/organisms/EventConfirmation.tsx
> +            cancel here
add a space after cancel here

2023-09-23 01:51 UTC, bananahz commented on frontend/src/pages/Test.tsx
since this page is for testing purposes, we can remove it from the PR too since we dont want Test to be pushed

2023-09-23 18:10 UTC, Y1chenYao approved these changes
Looks pretty good!

2023-09-23 19:09 UTC, bananahz approved these changes
lgtm :)

2023-09-23 19:35 UTC, akinfelami approved these changes
lgtm

2023-09-24 03:54 UTC, jasozh approved these changes
Good work. Things to note:
- Remember to delete unused imports
- Although the Figma shows a gray box, remember that at the end of the day, we're passing in the `EventDetails` component into the slot where the gray box is. Use the gray box as a reference while testing (and leave it in for the PR), but also include the actual component (in this case `EventDetails`) in the future.

2023-10-08 22:24 UTC, merged